services:
    web:
        image: nginx:latest
        container_name: ${WEBSERVER_CONTAINER_NAME}
        # restart: always
        ports:
        - ${WEBSERVER_PORT}:80
        volumes:
        - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        - ./docker/nginx/logs:/var/log/nginx
        - ./:/var/www/html
        depends_on:
        - app
        - database

    app:
        build: ./docker/php
        container_name: ${APP_CONTAINER_NAME}
        volumes:
        - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        - ./:/var/www/html

    database:
        image: mysql:8.3.0
        container_name: ${DB_CONTAINER_NAME}
        ports:
        - ${MYSQL_PORT}:3306
        volumes:
        - ./docker/mysql:/var/lib/mysql
        environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${PHPMYADMIN_CONTAINER_NAME}
        ports:
        - ${PHPMYADMIN_PORT}:80
        environment:
        - PMA_HOST=database
        - PMA_PORT=3306
        - PMA_USER=${MYSQL_USER}
        - PMA_PASSWORD=${MYSQL_PASSWORD}